version: '3.8'

services:
  sms-backend:
    image: sladeghost/sms-backend:latest
    container_name: sms-backend-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: "postgresql://neondb_owner:npg_7pSu1ODEvjwL@ep-tight-morning-a56ez346-pooler.us-east-2.aws.neon.tech/sms?sslmode=require"
      DIRECT_URL: "postgresql://neondb_owner:npg_7pSu1ODEvjwL@ep-tight-morning-a56ez346-pooler.us-east-2.aws.neon.tech/sms?sslmode=require"
      JWT_SECRET: "thisschoolsappisbest"
      FIRST_SM_EMAIL: "supermanager@school.com"
      FIRST_SM_PASSWORD: "SuperManager@123"
      FIRST_SM_USER_ID: "1"
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge
