-- AlterEnum
-- This migration adds new values to the Role enum.
-- Each ALTER TYPE ... ADD VALUE statement must run in its own transaction.
ALTER TYPE "Role" ADD VALUE 'SENIOR_DISCIPLINE_MASTER';
ALTER TYPE "Role" ADD VALUE 'DEAN_OF_DISCIPLINE';
ALTER TYPE "Role" ADD VALUE 'DEAN_OF_STUDIES';
ALTER TYPE "Role" ADD VALUE 'FEE_AUDITOR';
ALTER TYPE "Role" ADD VALUE 'SECRETARY';
ALTER TYPE "Role" ADD VALUE 'NURSE';

-- AlterEnum
ALTER TYPE "AssignmentRole" ADD VALUE 'SENIOR_DISCIPLINE_MASTER';
ALTER TYPE "AssignmentRole" ADD VALUE 'DEAN_OF_DISCIPLINE';
ALTER TYPE "AssignmentRole" ADD VALUE 'DEAN_OF_STUDIES';
ALTER TYPE "AssignmentRole" ADD VALUE 'FEE_AUDITOR';
ALTER TYPE "AssignmentRole" ADD VALUE 'SECRETARY';
ALTER TYPE "AssignmentRole" ADD VALUE 'NURSE';
